- name: Install dev toolset
  hosts: all
  gather_facts: yes
  tasks:
    - name: Include OS-specific tasks for macOS
      include_role:
        name: macos
      when: ansible_system == 'Darwin'

    - name: Include OS-specific tasks for Ubuntu
      include_role:
        name: ubuntu
      when: ansible_os_family == 'Debian'