---
- name: Install Podman Desktop using Flatpak
  hosts: all
  become: true
  tasks:
    # Install flatpak and flathub
    - name: Install flatpak
      apt: 
        name: flatpak
        state: present

    - name: Install flathub remote
      command: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo

    # Install Podman Desktop
    - name: Install Podman Desktop (Wait for remote)
      command: sleep 60 && flatpak install --user -y io.containers.podman.desktop
      when: inventory_hostname != 'localhost'


    # Grant access to system resources (optional)
    - name: Allow access to system resources (optional)
      command: flatpak --user override --filesystem=host 
      when: not ansible_virtualization_type in ['docker', 'lxc']
