---
- name: Install Podman on Ubuntu
  package:
    name: podman
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install podman-compose
  ansible.builtin.pip:
    name: podman-compose
    state: present
  become: yes
  when: ansible_os_family == "Debian" 

- name: Add flathub remote
  command: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo

# Install Podman Desktop
- name: Install Podman Desktop
  command: flatpak install --user -y io.podman_desktop.PodmanDesktop

- name: Check Podman Status
  command: podman --version
  register: podman_status
  ignore_errors: true

- name: Check Podman Compose Status
  command: podman-compose --version
  register: podman_compose_status
  ignore_errors: true

- name: Check Podman Desktop Status
  command: flatpak list
  register: flatpak_list_output
  changed_when: false

- name: Print Status
  debug:
    msg: |
      Podman Status: {{ 'Installed and Running' if podman_status.rc == 0 else 'Not Installed or Not Running' }}
      Podman Compose Status: {{ 'Installed and Running' if podman_compose_status.rc == 0 else 'Not Installed or Not Running' }}
      Podman Desktop Status: {{ 'Installed' if 'io.podman_desktop.PodmanDesktop' in flatpak_list_output.stdout else 'Not Installed' }}