---
- name: Install required packages
  package:
    name: slirp4netns
    state: present

- name: Add subuids and subgids for root user
  command: "usermod --add-subuids 100000-165535 --add-subgids 100000-165535 root"
  become_user: root

- name: Add additional group for root user
  command: "usermod --add-subgids 2000-2000 root"
  become_user: root

- name: Enable unprivileged ping
  block:
    - name: Check if ping_group_range already set
      command: "grep '^net.ipv4.ping_group_range' /etc/sysctl.conf"
      register: ping_group_range_check
      failed_when: false

    - name: Set ping_group_range
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ping_group_range=0 2000000"
        create: yes
      when: ping_group_range_check.rc != 0

    - name: Apply changes to sysctl
      command: "sysctl -p"

